// scripts/generate-seed.js
// Usage:
//   node scripts/generate-seed.js > migrations/0002_seed.sql
//   wrangler d1 execute sa-fuel-prices --file=migrations/0002_seed.sql

const path = require('path');
const data = require(path.join(__dirname, '../data/prices.json'));

const MONTHS = {
  Jan:'01', Feb:'02', Mar:'03', Apr:'04',
  May:'05', Jun:'06', Jul:'07', Aug:'08',
  Sep:'09', Oct:'10', Nov:'11', Dec:'12',
};

function toISO(label) {
  const [mon, year] = label.trim().split(' ');
  return `${year}-${MONTHS[mon]}`;
}

const lines = data.map(row => {
  const month = toISO(row.month);
  return `INSERT OR REPLACE INTO fuel_prices ` +
    `(month, month_label, p95i, p95c, p93i, d500i, d500c, d50i, d50c) VALUES ` +
    `('${month}','${row.month}',${row.p95i},${row.p95c},${row.p93i},` +
    `${row.d500i},${row.d500c},${row.d50i},${row.d50c});`;
});

console.log('-- SA Fuel Prices seed data — generated by scripts/generate-seed.js');
console.log('-- ' + new Date().toISOString());
console.log('-- Diesel grades: 500ppm (standard) and 50ppm (low sulphur)');
console.log('-- Note: 50ppm values pre-2025 are estimates (+R0.10 premium over 500ppm)');
console.log('');
lines.forEach(l => console.log(l));
console.log('');
console.log('-- ' + data.length + ' rows inserted');
